[command]
default=true

[file:${CYLC_WORKFLOW_RUN_DIR}/lib/python/amip_ancil]
source=${GIT_AMIP_SCRIPTS_CLONE_DIR}/Projects/CMIP/CMIP7/observed_sst_si/site/nci-gadi

[file:${CYLC_WORKFLOW_SHARE_DIR}/amip_seaice.nc]
source=${SEAICE_DIRPATH}/${SEAICE_FILENAME}
mode=symlink

[file:${CYLC_WORKFLOW_SHARE_DIR}/amip_sst.nc]
source=${SST_DIRPATH}/${SST_FILENAME}
mode=symlink
