repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: name-tests-test
    -   id: debug-statements
    -   id: requirements-txt-fixer
# Run linter and formatter.
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.12.4'
    hooks:
    # Run the linter
    -   id: ruff-check
        types_or: [ python, pyi ] # Exclude jupyter notebooks
        args: ['--fix']
    -   id: ruff-format
        types_or: [ python, pyi ] # Exclude jupyter notebooks