# Interpolate CMIP7 SM Biomass burning emissions to ESM1.6 grid

"""Command-line helper for ScenarioMIP biomass burning aerosol interpolation.

This module drives the CMIP7 ScenarioMIP aerosol biomass-burning workflow for
ESM1.6. It assembles file paths, loads BC/OC emission datasets, partitions low
and high injection height emissions, regrids the results to the target model
grid, cleans pole values, labels output STASH metadata, and writes UM ancillary
files.
"""

from argparse import ArgumentParser
from datetime import datetime
from pathlib import Path

import iris
import netCDF4
from aerosol.cmip7_aerosol_common import (
    load_cmip7_aerosol,
    zero_poles,
)
from aerosol.cmip7_SM_aerosol import esm_sm_aerosol_save_dirpath
from cmip7_ancil_argparse import common_parser
from cmip7_ancil_common import (
    INTERPOLATION_SCHEME,
    cmip7_date_constraint_from_years,
    esm_grid_mask_cube,
    extend_years,
    interpolate_monthly,
    save_ancil,
    set_coord_system,
)
from cmip7_SM import CMIP7_SM_BEG_YEAR, CMIP7_SM_END_YEAR


def parse_args():
    '''
    Parse command line arguments for CMIP7 ScenarioMIP aerosol biomass burning.
    '''
    parser = ArgumentParser(
        prog="cmip7_SM_Bio_interpolate",
        description=(
            "Generate input files from CMIP7 ScenarioMIP biomass forcings"
        ),
        parents=[common_parser()],
    )
    parser.add_argument("--scenario")
    parser.add_argument("--dataset-date-range")
    parser.add_argument("--save-filename")
    return parser.parse_args()


def _biomass_variable(species):
    '''
    Return the variable name for the given species in the CMIP7 ScenarioMIP biomass burning dataset.
    '''
    return f"{species}-em-openburning"


def _biomass_dirpath(args, species):
    '''
    Return the directory path to the CMIP7 ScenarioMIP biomass burning aerosol emissions data for the given species.
    '''
    return (
        Path(args.cmip7_source_data_dirname)
        / "ScenarioMIP"
        / "IIASA-IAMC"
        / args.dataset_version
        / "atmos"
        / "mon"
        / _biomass_variable(species).replace("-", "_")
        / "gn"
        / args.dataset_vdate
    )


def cmip7_sm_aerosol_biomass_filepath(args, species, date_range):
    '''
    Return the file path to the CMIP7 ScenarioMIP biomass burning aerosol 
    emissions data for the given species and date range.
    '''
    dirpath = _biomass_dirpath(args, species)
    filename = (
        f"{_biomass_variable(species)}_input4MIPs_emissions_ScenarioMIP_"
        f"{args.dataset_version}_gn_"
        f"{date_range}.nc"
    )
    return dirpath / filename


def load_cmip7_aerosol_biomass(args, species, date_range, constraint):
    """
    Load ScenarioMIP biomass-burning aerosol data and fill missing ocean values.

    This loader reads BC or OC emissions from the CMIP7 ScenarioMIP dataset,
    applies the requested time constraint, and fills missing data over oceans
    with zero because the model expects full global coverage.
    """
    cube = load_cmip7_aerosol(
        args, cmip7_sm_aerosol_biomass_filepath, species, date_range, constraint
    )
    # This data is missing over oceans,
    # so needs to be filled with zero for the model
    cube.data = cube.data.filled(0.0)
    return cube


def load_sector_dict(args, filepath_fn):
    """
    Read the ScenarioMIP sector mapping from the input file metadata.

    The ScenarioMIP biomass burning dataset stores sector information in a
    text attribute rather than a standard Iris coordinate, so this function
    opens the NetCDF file with netCDF4 and converts the sector list into a
    lookup dictionary.
    """
    # Iris doesn't read the sector coordinate so use netCDF4
    date_range = args.dataset_date_range
    d = netCDF4.Dataset(filepath_fn(args, "BC", date_range))
    sectord = dict()
    for s in d["sector"].ids.split(";"):
        i, name = s.split(":")
        sectord[name.strip()] = int(i)
    d.close()
    return sectord


# When True, force load the low/high cubes so timing and memory behavior can
# be observed before expensive regridding and saving.
force_load = True


def split_sm_low_high(bc_cube, oc_cube, sector_dict):
    """
    Based on code generated by Gemini Flash 3.5.

    Slices and sums the 4D ScenarioMIP BC and OC emission cubes to partition
    low-level and high-level injection height emissions.

    Dimensions of input cubes: (time, sector, lat, lon)
    Sectors:
    0: Agricultural Waste Burning;
    1: Forest Burning;
    2: Grassland Burning;
    3: Peat Burning
    """
    agri = sector_dict["Agricultural Waste Burning"]
    fore = sector_dict["Forest Burning"]
    sava = sector_dict["Grassland Burning"]
    peat = sector_dict["Peat Burning"]

    # Sum low-level sectors using collapsed:
    low_sectors = [agri, sava, peat]
    bc_low = bc_cube[:, low_sectors].collapsed("sector", iris.analysis.SUM)
    oc_low = oc_cube[:, low_sectors].collapsed("sector", iris.analysis.SUM)

    # Extract high-level sector:
    bc_high = bc_cube[:, fore]
    oc_high = oc_cube[:, fore]

    # Remove the scalar sector coordinate from the sliced cubes to prevent
    # coordinate mismatch warnings when summing or saving
    for cube in (bc_low, oc_low, bc_high, oc_high):
        if cube.coords("sector"):
            cube.remove_coord("sector")

    # Combine the species into bulk low and high emission cubes
    low = bc_low + oc_low
    high = bc_high + oc_high

    return low, high


def save_cmip7_aerosol_biomass(args, filepath_fn, load_fn, save_dirpath):
    """
    Load, process and save ScenarioMIP biomass burning low/high aerosol fields.

    This function drives the full biomass burning ancillary creation path. It
    loads BC and OC emissions, partitions them into low- and high-altitude
    injection categories, regrids the results to the ESM1.6 grid, zeros the
    pole rows, attaches the correct STASH metadata, and writes the ancillary
    files to the output directory.
    """
    # Load the raw BC and OC biomass burning cubes using the provided loader.
    bc = load_fn(args, "BC")
    oc = load_fn(args, "OC")

    # Load the sector mapping required to partition the data into low/high.
    sector_dict = load_sector_dict(args, filepath_fn)

    # Split the loaded species into bulk low-level and high-level emission fields.
    low, high = split_sm_low_high(bc, oc, sector_dict)

    if force_load:
        # Force data evaluation now so timing/memory behavior is visible before
        # expensive regridding and saving operations.
        _ = low.data
        _ = high.data
        now = datetime.now()
        print(f"{now}: LO, HI done")

    # Regridding requires matching coordinate systems.
    set_coord_system(low)
    set_coord_system(high)

    now = datetime.now()
    print(f"{now}: set_coord_system done")

    # Regrid each split field to the target ESM1.6 grid using the shared scheme.
    esm_grid_mask = esm_grid_mask_cube(args)
    low_esm = low.regrid(esm_grid_mask, INTERPOLATION_SCHEME)
    high_esm = high.regrid(esm_grid_mask, INTERPOLATION_SCHEME)

    now = datetime.now()
    print(f"{now}: regrid done")

    # Zero any polar rows.
    zero_poles(low_esm)
    zero_poles(high_esm)

    now = datetime.now()
    print(f"{now}: zero_poles done")

    # Attach UM STASH metadata so the saved ancillary fields are labeled correctly.
    low_esm.attributes["STASH"] = iris.fileformats.pp.STASH(
        model=1, section=0, item=130
    )
    high_esm.attributes["STASH"] = iris.fileformats.pp.STASH(
        model=1, section=0, item=131
    )

    # Write both output fields to the destination directory.
    save_ancil([low_esm, high_esm], save_dirpath, args.save_filename)

    now = datetime.now()
    print(f"{now}: save_ancil done")


def load_cmip7_sm_aerosol_biomass(args, species):
    """
    Load and prepare ScenarioMIP biomass burning aerosol input for interpolation.

    This wrapper loads the requested species cube with the ScenarioMIP time
    constraint for the ScenarioMIP time window, performs monthly interpolation
    to fill gaps, and extends the time series by duplicating the first and
    last year boundaries.

    """
    # Load the selected CMIP7 biomass burning aerosol cube using the SM time constraint.
    cube = load_cmip7_aerosol_biomass(
        args,
        species,
        args.dataset_date_range,
        cmip7_date_constraint_from_years(
            CMIP7_SM_BEG_YEAR,
            CMIP7_SM_END_YEAR,
        ),
    )

    # Fill any missing monthly values by linear interpolation for each month.
    interpolated = interpolate_monthly(
        cube, CMIP7_SM_BEG_YEAR, CMIP7_SM_END_YEAR
    )

    # Extend the series by duplicating the first and last year.
    return extend_years(interpolated)


if __name__ == "__main__":
    '''
    Interpolate CMIP7 ScenarioMIP biomass burning emissions to ESM1.6 grid.
    '''
    args = parse_args()

    save_cmip7_aerosol_biomass(
        args,
        cmip7_sm_aerosol_biomass_filepath,
        load_cmip7_sm_aerosol_biomass,
        esm_sm_aerosol_save_dirpath(args),
    )
