# Interpolate CMIP7 SM Biomass burning emissions to ESM1.6 grid

from argparse import ArgumentParser
from datetime import datetime
from pathlib import Path

import iris
import netCDF4
from aerosol.cmip7_aerosol_common import (
    load_cmip7_aerosol,
    zero_poles,
)
from aerosol.cmip7_SM_aerosol import esm_sm_aerosol_save_dirpath
from cmip7_ancil_argparse import common_parser
from cmip7_ancil_common import (
    INTERPOLATION_SCHEME,
    cmip7_date_constraint_from_years,
    esm_grid_mask_cube,
    extend_years,
    save_ancil,
    set_coord_system,
)
from cmip7_SM import CMIP7_SM_BEG_YEAR, CMIP7_SM_END_YEAR


def parse_args():
    parser = ArgumentParser(
        prog="cmip7_SM_Bio_interpolate",
        description=(
            "Generate input files from CMIP7 ScenarioMIP biomass forcings"
        ),
        parents=[common_parser()],
    )
    parser.add_argument("--scenario")
    parser.add_argument("--dataset-date-range")
    parser.add_argument("--save-filename")
    return parser.parse_args()


def _biomass_variable(species):
    return f"{species}-em-openburning"


def _biomass_dirpath(args, species):
    return (
        Path(args.cmip7_source_data_dirname)
        / "ScenarioMIP"
        / "IIASA-IAMC"
        / args.dataset_version
        / "atmos"
        / "mon"
        / _biomass_variable(species).replace("-", "_")
        / "gn"
        / args.dataset_vdate
    )


def cmip7_sm_aerosol_biomass_filepath(args, species, date_range):
    dirpath = _biomass_dirpath(args, species)
    filename = (
        f"{_biomass_variable(species)}_input4MIPs_emissions_ScenarioMIP_"
        f"{args.dataset_version}_gn_"
        f"{date_range}.nc"
    )
    return dirpath / filename


def load_cmip7_aerosol_biomass(args, species, date_range, constraint):
    cube = load_cmip7_aerosol(
        args, cmip7_sm_aerosol_biomass_filepath, species, date_range, constraint
    )
    # This data is missing over oceans,
    # so needs to be filled with zero for the model
    cube.data = cube.data.filled(0.0)
    return cube


def load_sector_dict(args, filepath_fn):
    # Iris doesn't read the sector coordinate so use netCDF4
    date_range = args.dataset_date_range
    d = netCDF4.Dataset(filepath_fn(args, "BC", date_range))
    sectord = dict()
    for s in d["sector"].ids.split(";"):
        i, name = s.split(":")
        sectord[name.strip()] = int(i)
    d.close()
    return sectord


force_load = True


def split_sm_low_high(bc_cube, oc_cube, sector_dict):
    """
    Based on code generated by Gemini Flash 3.5.

    Slices and sums the 4D ScenarioMIP BC and OC emission cubes to partition
    low-level and high-level injection height emissions.

    Dimensions of input cubes: (time, sector, lat, lon)
    Sectors:
    0: Agricultural Waste Burning;
    1: Forest Burning;
    2: Grassland Burning;
    3: Peat Burning
    """
    agri = sector_dict["Agricultural Waste Burning"]
    fore = sector_dict["Forest Burning"]
    sava = sector_dict["Grassland Burning"]
    peat = sector_dict["Peat Burning"]

    # Sum low-level sectors using collapsed:
    low_sectors = [agri, sava, peat]
    bc_low = bc_cube[:, low_sectors].collapsed("sector", iris.analysis.SUM)
    oc_low = oc_cube[:, low_sectors].collapsed("sector", iris.analysis.SUM)

    # Extract high-level sector:
    bc_high = bc_cube[:, fore]
    oc_high = oc_cube[:, fore]

    # Remove the scalar sector coordinate from the sliced cubes to prevent
    # coordinate mismatch warnings when summing or saving
    for cube in (bc_low, oc_low, bc_high, oc_high):
        if cube.coords("sector"):
            cube.remove_coord("sector")

    # Combine the species into bulk low and high emission cubes
    low = bc_low + oc_low
    high = bc_high + oc_high

    return low, high


def save_cmip7_aerosol_biomass(args, filepath_fn, load_fn, save_dirpath):
    bc = load_fn(args, "BC")
    oc = load_fn(args, "OC")

    sector_dict = load_sector_dict(args, filepath_fn)

    low, high = split_sm_low_high(bc, oc, sector_dict)

    if force_load:
        _ = low.data
        _ = high.data
        now = datetime.now()
        print(f"{now}: LO, HI done")

    # Regrid requires matching coordinate systems
    set_coord_system(low)
    set_coord_system(high)

    now = datetime.now()
    print(f"{now}: set_coord_system done")

    esm_grid_mask = esm_grid_mask_cube(args)
    low_esm = low.regrid(esm_grid_mask, INTERPOLATION_SCHEME)
    high_esm = high.regrid(esm_grid_mask, INTERPOLATION_SCHEME)

    now = datetime.now()
    print(f"{now}: regrid done")

    zero_poles(low_esm)
    zero_poles(high_esm)

    now = datetime.now()
    print(f"{now}: zero_poles done")

    low_esm.attributes["STASH"] = iris.fileformats.pp.STASH(
        model=1, section=0, item=130
    )
    high_esm.attributes["STASH"] = iris.fileformats.pp.STASH(
        model=1, section=0, item=131
    )

    save_ancil([low_esm, high_esm], save_dirpath, args.save_filename)

    now = datetime.now()
    print(f"{now}: save_ancil done")


def load_cmip7_sm_aerosol_biomass(args, species):
    cube = load_cmip7_aerosol_biomass(
        args,
        species,
        args.dataset_date_range,
        cmip7_date_constraint_from_years(
            CMIP7_SM_BEG_YEAR,
            CMIP7_SM_END_YEAR,
        ),
    )
    return extend_years(cube)


if __name__ == "__main__":
    args = parse_args()

    save_cmip7_aerosol_biomass(
        args,
        cmip7_sm_aerosol_biomass_filepath,
        load_cmip7_sm_aerosol_biomass,
        esm_sm_aerosol_save_dirpath(args),
    )
