per_cell:
  - "SOIL LAYER 1 TEMPERATURE ON TILES"
  - "SOIL LAYER 2 TEMPERATURE ON TILES"
  - "SOIL LAYER 3 TEMPERATURE ON TILES"
  - "SOIL LAYER 4 TEMPERATURE ON TILES"
  - "SOIL LAYER 5 TEMPERATURE ON TILES"
  - "SOIL LAYER 6 TEMPERATURE ON TILES"
  - "SOIL MOISTURE LAYER 1 (ON TILES)"
  - "SOIL MOISTURE LAYER 2 (ON TILES)"
  - "SOIL MOISTURE LAYER 3 (ON TILES)"
  - "SOIL MOISTURE LAYER 4 (ON TILES)"
  - "SOIL MOISTURE LAYER 5 (ON TILES)"
  - "SOIL MOISTURE LAYER 6 (ON TILES)"
  - "SOIL RESPIRATION ON TILES (CASA-CNP)"
  - "PLANT RESPIRATION ON TILES (CASA)"
  - "NET PRIMARY PRODUCTIVITY (NPP)"
  - "CANOPY CAPACITY ON TILES  KG PER M2"
  - "SURFACE TEMPERATURE ON TILES       K"
  - "ROUGHNESS LENGTH ON TILES          M"
  - "TILE MODIFIED INFILTRATION RATE"
  - "DOWNWARD SW RADIATION ON TILES  W PER M2"
  - "SNOW TEMPERATURE LAYER 1 (ON TILES)"
  - "SNOW TEMPERATURE LAYER 2 (ON TILES)"
  - "SNOW TEMPERATURE LAYER 3 (ON TILES)"

per_tile:
  - "CARBON POOL LABILE ON TILES"
  - "CARBON POOL PLANT - LEAF ON TILES"
  - "CARBON POOL PLANT - WOOD ON TILES"
  - "CARBON POOL PLANT - ROOT ON TILES"
  - "CARBON POOL LITTER - METB ON TILES"
  - "CARBON POOL LITTER - STR ON TILES"
  - "CARBON POOL LITTER - CWD ON TILES"
  - "CARBON POOL SOIL - MIC ON TILES"
  - "CARBON POOL SOIL - SLOW ON TILES"
  - "CARBON POOL SOIL - PASS ON TILES"
  - "NITROGEN POOL PLANT - LEAF ON TILES"
  - "NITROGEN POOL PLANT - WOOD ON TILES"
  - "NITROGEN POOL PLANT - ROOT ON TILES"
  - "NITROGEN POOL LITTER - METB ON TILES"
  - "NITROGEN POOL LITTER - STR ON TILES"
  - "NITROGEN POOL LITTER - CWD ON TILES"
  - "NITROGEN POOL SOIL - MIC ON TILES"
  - "NITROGEN POOL SOIL - SLOW ON TILES"
  - "NITROGEN POOL SOIL - PASS ON TILES"
  - "NITROGEN POOL SOIL MINIMUM (TILES)"
  - "PHOSPHORUS POOL PLANT - LEAF (TILES)"
  - "PHOSPHORUS POOL PLANT - WOOD (TILES)"
  - "PHOSPHORUS POOL PLANT - ROOT (TILES)"
  - "PHOSPHORUS POOL LITTER- METB (TILES)"
  - "PHOSPHORUS POOL LITTER - STR (TILES)"
  - "PHOSPHORUS POOL LITTER - CWD (TILES)"
  - "PHOSPHORUS POOL SOIL - MIC (TILES)"
  - "PHOSPHORUS POOL SOIL - SLOW (TILES)"
  - "PHOSPHORUS POOL SOIL - PASS (TILES)"
  - "PHOSPHORUS POOL SOIL LABILE (TILES)"
  - "PHOSPHORUS POOL SOIL SORB ON TILES"
  - "PHOSPHORUS POOL SOIL OCC ON TILES"
  - "LEAF AREA INDEX (CASA-CNP GLAI)"

vegetation_map:
  10: [6, 7, 9]
search_radius: 2
latitude_band: 8
minimum_points: 1
