[command]
default=python_env python -m ozone_ancil.ozone_cmip6_ancillary_for_suite \
       =${sources_ozone} \
       =-o ${output_root_timeseries} \
       =--tempfile ${sources_temp} \
       =--target-grid-orog=${target_grid_orog} \
       =--levelfile ${level_file} \
       =-b ${start_year} \
       =-e ${end_year} \
       =--extend_data ${extend_data} \
       =--calendar ${calendar} \
       =--timeaxis ${timeaxis}


[file:${output_root_timeseries}]
mode=mkdir
