[template variables=SITE]
compulsory=true
description=
help=Select the site at which model is being run.
ns=Compute host
sort-key=0
title=Site
value-titles=NCI-GADI
values='nci-gadi'

[template variables=ANCIL_CREATE_AEROSOL]
compulsory=true
description=Create Aerosol ancillaries
help=
ns=ANCILS
sort-key=
title=Aerosol ancillaries
type=boolean

[template variables=ANCIL_CREATE_GHG]
compulsory=true
description=Create GreenhouseGases ancillaries
help=
ns=ANCILS
sort-key=
title=GreenhouseGases
type=boolean

[template variables=TESTING]
compulsory=true
description=Perform rose-ana testing on resulting ancillaries
help=The ancillaries produced from this suite will be compared to reference
    =ancillaries.
ns=Testing
sort-key=a
title=Compare ancillaries to reference
type=boolean

